CREATE TABLE `foods` (
	`id` int AUTO_INCREMENT NOT NULL,
	`personalId` int,
	`name` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`category` varchar(100) NOT NULL,
	`subcategory` varchar(100),
	`source` enum('taco','usda','custom') NOT NULL DEFAULT 'custom',
	`sourceId` varchar(50),
	`servingSize` decimal(8,2) NOT NULL DEFAULT '100',
	`servingUnit` varchar(20) DEFAULT 'g',
	`householdMeasure` varchar(100),
	`householdGrams` decimal(8,2),
	`calories` decimal(8,2),
	`protein` decimal(8,2),
	`carbohydrates` decimal(8,2),
	`fiber` decimal(8,2),
	`totalFat` decimal(8,2),
	`saturatedFat` decimal(8,2),
	`monounsaturatedFat` decimal(8,2),
	`polyunsaturatedFat` decimal(8,2),
	`transFat` decimal(8,2),
	`cholesterol` decimal(8,2),
	`sugar` decimal(8,2),
	`vitaminA` decimal(10,4),
	`vitaminB1` decimal(10,4),
	`vitaminB2` decimal(10,4),
	`vitaminB3` decimal(10,4),
	`vitaminB5` decimal(10,4),
	`vitaminB6` decimal(10,4),
	`vitaminB9` decimal(10,4),
	`vitaminB12` decimal(10,4),
	`vitaminC` decimal(10,4),
	`vitaminD` decimal(10,4),
	`vitaminE` decimal(10,4),
	`vitaminK` decimal(10,4),
	`calcium` decimal(10,4),
	`iron` decimal(10,4),
	`magnesium` decimal(10,4),
	`phosphorus` decimal(10,4),
	`potassium` decimal(10,4),
	`sodium` decimal(10,4),
	`zinc` decimal(10,4),
	`copper` decimal(10,4),
	`manganese` decimal(10,4),
	`selenium` decimal(10,4),
	`iodine` decimal(10,4),
	`water` decimal(8,2),
	`ash` decimal(8,2),
	`glycemicIndex` int,
	`isActive` boolean NOT NULL DEFAULT true,
	`imageUrl` varchar(500),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `foods_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lab_exams` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentId` int NOT NULL,
	`personalId` int NOT NULL,
	`examDate` date NOT NULL,
	`labName` varchar(255),
	`hemoglobin` decimal(5,2),
	`hematocrit` decimal(5,2),
	`redBloodCells` decimal(5,2),
	`whiteBloodCells` decimal(8,0),
	`platelets` decimal(8,0),
	`totalCholesterol` decimal(6,2),
	`hdlCholesterol` decimal(6,2),
	`ldlCholesterol` decimal(6,2),
	`vldlCholesterol` decimal(6,2),
	`triglycerides` decimal(6,2),
	`fastingGlucose` decimal(6,2),
	`hba1c` decimal(4,2),
	`insulin` decimal(6,2),
	`homaIr` decimal(5,2),
	`creatinine` decimal(5,2),
	`urea` decimal(6,2),
	`uricAcid` decimal(5,2),
	`ast` decimal(6,2),
	`alt` decimal(6,2),
	`ggt` decimal(6,2),
	`alkalinePhosphatase` decimal(6,2),
	`totalBilirubin` decimal(5,2),
	`albumin` decimal(5,2),
	`tsh` decimal(6,3),
	`t4Free` decimal(5,3),
	`t3Free` decimal(5,3),
	`vitaminD` decimal(6,2),
	`vitaminB12` decimal(8,2),
	`ferritin` decimal(8,2),
	`serumIron` decimal(6,2),
	`folicAcid` decimal(6,2),
	`testosterone` decimal(8,2),
	`cortisol` decimal(6,2),
	`crp` decimal(6,3),
	`fileUrl` varchar(500),
	`notes` text,
	`aiInterpretation` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lab_exams_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meal_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mealId` int NOT NULL,
	`foodId` int,
	`recipeId` int,
	`quantity` decimal(10,2) NOT NULL,
	`unit` varchar(50) DEFAULT 'g',
	`calories` decimal(10,2),
	`protein` decimal(10,2),
	`carbs` decimal(10,2),
	`fat` decimal(10,2),
	`fiber` decimal(10,2),
	`notes` varchar(255),
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `meal_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meal_plan_days` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mealPlanId` int NOT NULL,
	`dayOfWeek` enum('monday','tuesday','wednesday','thursday','friday','saturday','sunday'),
	`dayNumber` int,
	`isTrainingDay` boolean DEFAULT false,
	`totalCalories` decimal(10,2),
	`totalProtein` decimal(10,2),
	`totalCarbs` decimal(10,2),
	`totalFat` decimal(10,2),
	`totalFiber` decimal(10,2),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `meal_plan_days_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meal_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`personalId` int NOT NULL,
	`studentId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`objective` enum('weight_loss','muscle_gain','maintenance','recomposition','bulking','cutting','health','sports_performance','therapeutic') DEFAULT 'maintenance',
	`startDate` date,
	`endDate` date,
	`status` enum('draft','active','paused','completed','archived') DEFAULT 'draft',
	`targetCalories` int,
	`targetProtein` int,
	`targetCarbs` int,
	`targetFat` int,
	`targetFiber` int,
	`targetWater` decimal(4,2),
	`proteinPercentage` int,
	`carbsPercentage` int,
	`fatPercentage` int,
	`mealsPerDay` int DEFAULT 5,
	`includeSnacks` boolean DEFAULT true,
	`restrictions` text,
	`allergies` text,
	`preferences` text,
	`dislikes` text,
	`adjustForTraining` boolean DEFAULT true,
	`trainingDayCaloriesBonus` int DEFAULT 0,
	`trainingDayCarbsBonus` int DEFAULT 0,
	`generatedByAI` boolean DEFAULT false,
	`aiPrompt` text,
	`aiVersion` varchar(50),
	`notes` text,
	`version` int DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `meal_plans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mealPlanDayId` int NOT NULL,
	`name` varchar(100) NOT NULL,
	`mealType` enum('breakfast','morning_snack','lunch','afternoon_snack','pre_workout','post_workout','dinner','supper','other') NOT NULL,
	`scheduledTime` varchar(5),
	`totalCalories` decimal(10,2),
	`totalProtein` decimal(10,2),
	`totalCarbs` decimal(10,2),
	`totalFat` decimal(10,2),
	`totalFiber` decimal(10,2),
	`notes` text,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `meals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nutrition_anamneses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentId` int NOT NULL,
	`personalId` int NOT NULL,
	`anamnesisId` int,
	`previousDiets` text,
	`dietHistory` text,
	`eatingDisorderHistory` boolean DEFAULT false,
	`eatingDisorderDetails` text,
	`mealsPerDay` int,
	`mealTimes` text,
	`eatingSpeed` enum('very_fast','fast','normal','slow','very_slow'),
	`chewingQuality` enum('poor','fair','good','excellent'),
	`eatingLocation` text,
	`eatingCompany` enum('alone','family','friends','coworkers','varies'),
	`screenWhileEating` boolean DEFAULT false,
	`favoritesFoods` text,
	`dislikedFoods` text,
	`foodCravings` text,
	`comfortFoods` text,
	`foodIntolerances` text,
	`foodAllergies` text,
	`allergySymptoms` text,
	`dietaryRestrictions` text,
	`religiousRestrictions` text,
	`ethicalRestrictions` text,
	`waterIntakeLiters` decimal(4,2),
	`beverageConsumption` text,
	`alcoholConsumption` enum('none','occasional','moderate','frequent'),
	`alcoholDetails` text,
	`currentSupplements` text,
	`previousSupplements` text,
	`supplementGoals` text,
	`digestiveIssues` text,
	`bowelFrequency` varchar(50),
	`bowelConsistency` enum('hard','normal','soft','liquid','varies'),
	`appetiteLevel` enum('very_low','low','normal','high','very_high'),
	`satietyLevel` enum('never_full','rarely_full','normal','easily_full','always_full'),
	`emotionalEating` boolean DEFAULT false,
	`emotionalEatingTriggers` text,
	`cookingSkills` enum('none','basic','intermediate','advanced'),
	`cookingFrequency` enum('never','rarely','sometimes','often','always'),
	`mealPrepTime` int,
	`kitchenEquipment` text,
	`monthlyFoodBudget` decimal(10,2),
	`budgetPriority` enum('very_limited','limited','moderate','flexible','unlimited'),
	`workSchedule` text,
	`mealPrepDay` text,
	`eatingOutFrequency` enum('never','rarely','weekly','often','daily'),
	`deliveryFrequency` enum('never','rarely','weekly','often','daily'),
	`nutritionGoals` text,
	`expectedResults` text,
	`timeline` varchar(100),
	`additionalNotes` text,
	`version` int DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nutrition_anamneses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nutrition_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentId` int NOT NULL,
	`personalId` int NOT NULL,
	`measurementId` int,
	`assessmentDate` date NOT NULL,
	`height` decimal(5,2),
	`weight` decimal(5,2),
	`bmi` decimal(4,2),
	`bmiClassification` varchar(50),
	`bodyFatPercentage` decimal(5,2),
	`muscleMass` decimal(5,2),
	`fatMass` decimal(5,2),
	`boneMass` decimal(5,2),
	`waterPercentage` decimal(5,2),
	`visceralFat` int,
	`waistCircumference` decimal(5,2),
	`hipCircumference` decimal(5,2),
	`waistHipRatio` decimal(4,3),
	`neckCircumference` decimal(5,2),
	`armCircumference` decimal(5,2),
	`bmr` int,
	`bmrFormula` varchar(50),
	`tdee` int,
	`activityLevel` enum('sedentary','light','moderate','active','very_active'),
	`recommendedCalories` int,
	`recommendedProtein` int,
	`recommendedCarbs` int,
	`recommendedFat` int,
	`cardiovascularRisk` enum('low','moderate','high','very_high'),
	`metabolicSyndromeRisk` boolean DEFAULT false,
	`clinicalObservations` text,
	`dietaryRecommendations` text,
	`aiAnalysis` text,
	`assessmentMethod` enum('bioimpedance','skinfold','dexa','hydrostatic','visual','other') DEFAULT 'bioimpedance',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nutrition_assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nutrition_guidelines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`personalId` int,
	`title` varchar(255) NOT NULL,
	`category` varchar(100),
	`content` text NOT NULL,
	`summary` text,
	`targetGoals` text,
	`targetConditions` text,
	`imageUrl` varchar(500),
	`isPublic` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`viewCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nutrition_guidelines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nutrition_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentId` int NOT NULL,
	`personalId` int NOT NULL,
	`mealPlanId` int,
	`logDate` date NOT NULL,
	`mealType` enum('breakfast','morning_snack','lunch','afternoon_snack','pre_workout','post_workout','dinner','supper','other') NOT NULL,
	`logTime` varchar(5),
	`foodId` int,
	`recipeId` int,
	`freeDescription` text,
	`quantity` decimal(10,2),
	`unit` varchar(50),
	`calories` decimal(10,2),
	`protein` decimal(10,2),
	`carbs` decimal(10,2),
	`fat` decimal(10,2),
	`fiber` decimal(10,2),
	`wasPlanned` boolean DEFAULT true,
	`adherenceScore` int,
	`hungerLevel` enum('very_hungry','hungry','neutral','satisfied','very_full'),
	`energyLevel` enum('very_low','low','normal','high','very_high'),
	`mood` enum('bad','neutral','good','excellent'),
	`notes` text,
	`photoUrl` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nutrition_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `nutrition_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`personalId` int NOT NULL,
	`defaultBmrFormula` enum('mifflin_st_jeor','harris_benedict','katch_mcardle','cunningham') DEFAULT 'mifflin_st_jeor',
	`defaultActivityMultiplier` decimal(3,2) DEFAULT '1.55',
	`defaultProteinPercentage` int DEFAULT 30,
	`defaultCarbsPercentage` int DEFAULT 40,
	`defaultFatPercentage` int DEFAULT 30,
	`proteinPerKgWeightLoss` decimal(3,2) DEFAULT '1.8',
	`proteinPerKgMuscleGain` decimal(3,2) DEFAULT '2.2',
	`proteinPerKgMaintenance` decimal(3,2) DEFAULT '1.6',
	`defaultCaloricDeficit` int DEFAULT 500,
	`defaultCaloricSurplus` int DEFAULT 300,
	`defaultMealsPerDay` int DEFAULT 5,
	`defaultMealNames` text,
	`trainingDayCaloriesBonus` int DEFAULT 200,
	`trainingDayCarbsBonus` int DEFAULT 50,
	`showMicronutrients` boolean DEFAULT true,
	`showGlycemicIndex` boolean DEFAULT false,
	`preferredFoodDatabase` enum('taco','usda','both') DEFAULT 'taco',
	`sendMealReminders` boolean DEFAULT false,
	`sendWeeklyReport` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `nutrition_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `nutrition_settings_personalId_unique` UNIQUE(`personalId`)
);
--> statement-breakpoint
CREATE TABLE `recipe_ingredients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`recipeId` int NOT NULL,
	`foodId` int NOT NULL,
	`quantity` decimal(10,2) NOT NULL,
	`unit` varchar(50) DEFAULT 'g',
	`notes` varchar(255),
	`calories` decimal(10,2),
	`protein` decimal(10,2),
	`carbs` decimal(10,2),
	`fat` decimal(10,2),
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `recipe_ingredients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `recipes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`personalId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`category` varchar(100),
	`tags` text,
	`prepTime` int,
	`cookTime` int,
	`servings` int DEFAULT 1,
	`servingSize` decimal(8,2),
	`difficulty` enum('easy','medium','hard') DEFAULT 'easy',
	`instructions` text,
	`tips` text,
	`totalCalories` decimal(10,2),
	`totalProtein` decimal(10,2),
	`totalCarbs` decimal(10,2),
	`totalFat` decimal(10,2),
	`totalFiber` decimal(10,2),
	`totalSodium` decimal(10,2),
	`imageUrl` varchar(500),
	`isPublic` boolean DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `recipes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `feature_flags` ADD `nutritionBetaEnabled` boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE `foods` ADD CONSTRAINT `foods_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `lab_exams` ADD CONSTRAINT `lab_exams_studentId_students_id_fk` FOREIGN KEY (`studentId`) REFERENCES `students`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `lab_exams` ADD CONSTRAINT `lab_exams_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `meal_items` ADD CONSTRAINT `meal_items_mealId_meals_id_fk` FOREIGN KEY (`mealId`) REFERENCES `meals`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `meal_items` ADD CONSTRAINT `meal_items_foodId_foods_id_fk` FOREIGN KEY (`foodId`) REFERENCES `foods`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `meal_items` ADD CONSTRAINT `meal_items_recipeId_recipes_id_fk` FOREIGN KEY (`recipeId`) REFERENCES `recipes`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `meal_plan_days` ADD CONSTRAINT `meal_plan_days_mealPlanId_meal_plans_id_fk` FOREIGN KEY (`mealPlanId`) REFERENCES `meal_plans`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `meal_plans` ADD CONSTRAINT `meal_plans_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `meal_plans` ADD CONSTRAINT `meal_plans_studentId_students_id_fk` FOREIGN KEY (`studentId`) REFERENCES `students`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `meals` ADD CONSTRAINT `meals_mealPlanDayId_meal_plan_days_id_fk` FOREIGN KEY (`mealPlanDayId`) REFERENCES `meal_plan_days`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_anamneses` ADD CONSTRAINT `nutrition_anamneses_studentId_students_id_fk` FOREIGN KEY (`studentId`) REFERENCES `students`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_anamneses` ADD CONSTRAINT `nutrition_anamneses_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_anamneses` ADD CONSTRAINT `nutrition_anamneses_anamnesisId_anamneses_id_fk` FOREIGN KEY (`anamnesisId`) REFERENCES `anamneses`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_assessments` ADD CONSTRAINT `nutrition_assessments_studentId_students_id_fk` FOREIGN KEY (`studentId`) REFERENCES `students`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_assessments` ADD CONSTRAINT `nutrition_assessments_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_assessments` ADD CONSTRAINT `nutrition_assessments_measurementId_measurements_id_fk` FOREIGN KEY (`measurementId`) REFERENCES `measurements`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_guidelines` ADD CONSTRAINT `nutrition_guidelines_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_logs` ADD CONSTRAINT `nutrition_logs_studentId_students_id_fk` FOREIGN KEY (`studentId`) REFERENCES `students`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_logs` ADD CONSTRAINT `nutrition_logs_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_logs` ADD CONSTRAINT `nutrition_logs_mealPlanId_meal_plans_id_fk` FOREIGN KEY (`mealPlanId`) REFERENCES `meal_plans`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_logs` ADD CONSTRAINT `nutrition_logs_foodId_foods_id_fk` FOREIGN KEY (`foodId`) REFERENCES `foods`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_logs` ADD CONSTRAINT `nutrition_logs_recipeId_recipes_id_fk` FOREIGN KEY (`recipeId`) REFERENCES `recipes`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `nutrition_settings` ADD CONSTRAINT `nutrition_settings_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `recipe_ingredients` ADD CONSTRAINT `recipe_ingredients_recipeId_recipes_id_fk` FOREIGN KEY (`recipeId`) REFERENCES `recipes`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `recipe_ingredients` ADD CONSTRAINT `recipe_ingredients_foodId_foods_id_fk` FOREIGN KEY (`foodId`) REFERENCES `foods`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `recipes` ADD CONSTRAINT `recipes_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;