CREATE TABLE `meal_plan_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`personalId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`objective` enum('weight_loss','muscle_gain','maintenance','recomposition','bulking','cutting','health','sports_performance','therapeutic') NOT NULL,
	`proteinPerKg` decimal(4,2) DEFAULT '2.0',
	`carbsPerKg` decimal(4,2) DEFAULT '3.0',
	`fatPerKg` decimal(4,2) DEFAULT '1.0',
	`calorieDeficit` int DEFAULT 0,
	`calorieSurplus` int DEFAULT 0,
	`mealsPerDay` int DEFAULT 5,
	`includeSnacks` boolean DEFAULT true,
	`restrictions` text,
	`preferences` text,
	`dislikes` text,
	`adjustForTraining` boolean DEFAULT true,
	`trainingDayCaloriesBonus` int DEFAULT 0,
	`trainingDayCarbsBonus` int DEFAULT 0,
	`notes` text,
	`tags` text,
	`difficulty` enum('beginner','intermediate','advanced') DEFAULT 'intermediate',
	`duration` varchar(50),
	`isActive` boolean NOT NULL DEFAULT true,
	`isSystem` boolean DEFAULT false,
	`usageCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `meal_plan_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `training_nutrition_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`personalId` int,
	`name` varchar(100) NOT NULL,
	`trainingType` enum('strength','cardio_low','cardio_high','mixed','rest','active_recovery','sports','competition') NOT NULL,
	`caloriesAdjustment` int DEFAULT 0,
	`caloriesAdjustmentPercent` decimal(5,2),
	`proteinAdjustment` decimal(5,2) DEFAULT '0',
	`carbsAdjustment` decimal(5,2) DEFAULT '0',
	`fatAdjustment` decimal(5,2) DEFAULT '0',
	`preWorkoutMealTiming` int DEFAULT 90,
	`postWorkoutMealTiming` int DEFAULT 30,
	`preWorkoutCarbs` decimal(5,2),
	`preWorkoutProtein` decimal(5,2),
	`postWorkoutCarbs` decimal(5,2),
	`postWorkoutProtein` decimal(5,2),
	`waterIntakeBonus` decimal(4,2) DEFAULT '0.5',
	`notes` text,
	`recommendations` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`isSystem` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `training_nutrition_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `meal_plan_templates` ADD CONSTRAINT `meal_plan_templates_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `training_nutrition_profiles` ADD CONSTRAINT `training_nutrition_profiles_personalId_personals_id_fk` FOREIGN KEY (`personalId`) REFERENCES `personals`(`id`) ON DELETE no action ON UPDATE no action;